#!/usr/bin/env python3
# scripts/generate_model.py
# Orchestrate: config YAML → .scad render → BOM extraction → DXF export

import sys, json, subprocess, argparse, tempfile, shutil, os
from pathlib import Path
from jinja2 import Template

p = argparse.ArgumentParser(description="Generate filterslang model from YAML config")
p.add_argument("--config", required=True, help="User config YAML file")
p.add_argument("--presets", required=True, help="Presets YAML file")
p.add_argument("--output-dir", default="out", help="Output directory")
p.add_argument("--skip-render", action="store_true", help="Skip OpenSCAD render (use existing .echo)")
p.add_argument("--skip-dxf", action="store_true", help="Skip DXF export")
p.add_argument("--skip-bom", action="store_true", help="Skip BOM extraction")
p.add_argument("--debug", action="store_true", help="Print extensive debug info")
args = p.parse_args()

output_dir = Path(args.output_dir)
output_dir.mkdir(parents=True, exist_ok=True)

DEBUG = args.debug or True  # Always enable for now

def debug_log(msg, level="INFO"):
    """Print debug message with level indicator."""
    prefix = f"[{level}]" if DEBUG else ""
    print(f"{prefix} {msg}", file=sys.stderr)

debug_log("=== GENERATE_MODEL DEBUG START ===")
debug_log(f"Current working directory: {os.getcwd()}", "DEBUG")
debug_log(f"Script location: {Path(__file__).absolute()}", "DEBUG")
debug_log(f"Output directory: {output_dir.absolute()}", "DEBUG")

# --- Step 1: Parse config → parameters ---
debug_log("", "INFO")
debug_log("[1/5] Parsing configuration...", "INFO")
debug_log(f"Config file: {args.config}", "DEBUG")
debug_log(f"Presets file: {args.presets}", "DEBUG")

config_json = output_dir / ".config_params.json"
cmd = [
    sys.executable, "scripts/config_to_params.py",
    "--config", args.config,
    "--presets", args.presets,
    "--output", str(config_json),
]
if args.debug:
    cmd.append("--debug")

debug_log(f"Running: {' '.join(cmd)}", "DEBUG")
result = subprocess.run(cmd, capture_output=True, text=True)
if result.returncode != 0:
    debug_log(f"STDERR: {result.stderr}", "ERROR")
    debug_log(f"STDOUT: {result.stdout}", "ERROR")
    sys.exit(1)

debug_log(result.stdout.strip(), "DEBUG")

params = json.loads(config_json.read_text(encoding="utf-8"))
config_name = params.get("bom_tag", "unnamed")
debug_log(f"Config name: {config_name}", "DEBUG")
debug_log(f"Parameters loaded: {list(params.keys())}", "DEBUG")

# --- Step 2: Generate OpenSCAD file in project root (for library resolution) ---
debug_log("", "INFO")
debug_log("[2/5] Generating OpenSCAD file...", "INFO")

scad_template = '''// Generated by config: {{ config_name }}
// DO NOT EDIT - Generated from {{ config_file }}
use <products/filterslang/filterslang.scad>;

filterslang(
  L={{ L }},
  D={{ D }},
  t={{ t }},
  medium="{{ medium }}",
  top="{{ top }}",
  open_top={{ open_top | default(false) | lower }},
  bottom="{{ bottom }}",
  bottom_opt="{{ bottom_opt | default('zonder') }}",
  rings_auto={{ rings_auto | default(true) | lower }},
  rings_count={{ rings_count | default(0) }},
  rings_positions={{ rings_positions | default([]) }},
  ring_w={{ ring_w | default(10) }},
  ring_t={{ ring_t | default(2) }},
  reinforce_enable={{ reinforce_enable | default(false) | lower }},
  reinforce_side="{{ reinforce_side | default('boven') }}",
  reinforce_spans={{ reinforce_spans | default([]) }},
  productzijde="{{ productzijde | default('buiten') }}",
  bom_tag="{{ bom_tag }}",
  $fn=96
);
'''

template = Template(scad_template)
scad_content = template.render(
    config_name=config_name,
    config_file=args.config,
    **params
)

# IMPORTANT: Generate in project root so that relative library paths resolve correctly
# OpenSCAD looks for `use <>` imports relative to the file being rendered
project_root = Path.cwd()
scad_file = project_root / f".gen_{config_name}.scad"
scad_file.write_text(scad_content, encoding="utf-8")
debug_log(f"Generated SCAD file: {scad_file.absolute()}", "DEBUG")
debug_log(f"SCAD file in project root for library resolution: {scad_file.name}", "DEBUG")
debug_log(f"SCAD file size: {len(scad_content)} bytes", "DEBUG")
debug_log(f"SCAD content (first 500 chars):\n{scad_content[:500]}", "DEBUG")

# --- Step 3: Render with OpenSCAD ---
if not args.skip_render:
    debug_log("", "INFO")
    debug_log("[3/5] Rendering with OpenSCAD...", "INFO")
    
    # Echo file goes to output_dir, but .scad stays in project root for library resolution
    echo_file = output_dir / f"{config_name}.echo"
    
    # Test: Try different ways to call OpenSCAD
    cwd = Path.cwd()
    debug_log(f"Working directory for OpenSCAD: {cwd}", "DEBUG")
    debug_log(f"Echo output file (absolute): {echo_file.absolute()}", "DEBUG")
    debug_log(f"SCAD file (absolute): {scad_file.absolute()}", "DEBUG")
    
    # Check if files exist
    debug_log(f"SCAD file exists: {scad_file.exists()}", "DEBUG")
    debug_log(f"products/filterslang/filterslang.scad exists (from cwd): {(cwd / 'products/filterslang/filterslang.scad').exists()}", "DEBUG")
    
    # Method 1: Use absolute paths, run from project root
    cmd = ["openscad", "-o", str(echo_file.absolute()), str(scad_file.absolute())]
    debug_log(f"OpenSCAD command: {' '.join(cmd)}", "DEBUG")
    debug_log(f"OpenSCAD running from: {cwd}", "DEBUG")
    
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(cwd))
    
    debug_log(f"OpenSCAD return code: {result.returncode}", "DEBUG")
    debug_log(f"OpenSCAD stdout:\n{result.stdout}", "DEBUG")
    debug_log(f"OpenSCAD stderr:\n{result.stderr}", "DEBUG")
    
    if result.returncode != 0:
        debug_log(f"OpenSCAD render failed (return code {result.returncode})", "ERROR")
        sys.exit(1)
    
    # Check echo file
    debug_log(f"Echo file exists after render: {echo_file.exists()}", "DEBUG")
    if echo_file.exists():
        echo_content = echo_file.read_text(encoding="utf-8", errors="ignore")
        debug_log(f"Echo file size: {len(echo_content)} bytes", "DEBUG")
        debug_log(f"Echo content (first 1000 chars):\n{echo_content[:1000]}", "DEBUG")
        debug_log(f"Echo contains 'BOM_ITEM': {'BOM_ITEM' in echo_content}", "DEBUG")
    
    debug_log(f"✓ Rendered to {echo_file}", "INFO")
else:
    echo_file = output_dir / f"{config_name}.echo"
    if not echo_file.exists():
        debug_log(f"ERROR: --skip-render but {echo_file} not found", "ERROR")
        sys.exit(1)
    debug_log(f"⊘ Skipping render; using {echo_file}", "INFO")

# --- Step 4: Extract BOM ---
if not args.skip_bom:
    debug_log("", "INFO")
    debug_log("[4/5] Extracting BOM...", "INFO")
    jsonl_file = output_dir / f"{config_name}_bom.jsonl"
    csv_file = output_dir / f"{config_name}_bom.csv"
    xlsx_file = output_dir / f"{config_name}_bom_production.xlsx"
    
    debug_log(f"Echo file for BOM: {echo_file}", "DEBUG")
    debug_log(f"Echo file exists: {echo_file.exists()}", "DEBUG")
    
    cmd = [
        sys.executable, "scripts/render_bom.py",
        "--product", "filterslang",
        "--version", "1.0.0",
        "--echo", str(echo_file),
        "--jsonl", str(jsonl_file),
        "--csv", str(csv_file),
        "--debug",
    ]
    
    debug_log(f"BOM extraction command: {' '.join(cmd)}", "DEBUG")
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    debug_log(f"BOM extraction return code: {result.returncode}", "DEBUG")
    debug_log(f"BOM extraction stdout:\n{result.stdout}", "DEBUG")
    debug_log(f"BOM extraction stderr:\n{result.stderr}", "DEBUG")
    
    if result.returncode != 0:
        debug_log(f"BOM extraction failed", "ERROR")
        sys.exit(1)
    
    # Also produce Excel BOM
    cmd = [
        sys.executable, "scripts/bom_producer.py",
        "--jsonl", str(jsonl_file),
        "--parts", "data/parts.csv",
        "--xlsx", str(xlsx_file),
    ]
    
    debug_log(f"BOM producer command: {' '.join(cmd)}", "DEBUG")
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    debug_log(f"BOM producer return code: {result.returncode}", "DEBUG")
    if result.returncode != 0:
        debug_log(f"BOM production stdout:\n{result.stdout}", "ERROR")
        debug_log(f"BOM production stderr:\n{result.stderr}", "ERROR")
        sys.exit(1)
    
    debug_log(f"✓ Extracted BOM to {jsonl_file}, {csv_file}, {xlsx_file}", "INFO")
else:
    debug_log("⊘ Skipping BOM extraction", "INFO")

# --- Step 5: Generate DXF (2D projection) ---
if not args.skip_dxf:
    debug_log("", "INFO")
    debug_log("[5/5] Generating DXF (2D projection)...", "INFO")
    
    dxf_template = '''// 2D projection for DXF export - {{ config_name }}
// DO NOT EDIT - Generated from {{ config_file }}
use <products/filterslang/filterslang.scad>;

projection(cut=false)
filterslang(
  L={{ L }},
  D={{ D }},
  t={{ t }},
  medium="{{ medium }}",
  top="{{ top }}",
  open_top={{ open_top | default(false) | lower }},
  bottom="{{ bottom }}",
  bottom_opt="{{ bottom_opt | default('zonder') }}",
  rings_auto={{ rings_auto | default(true) | lower }},
  rings_count={{ rings_count | default(0) }},
  rings_positions={{ rings_positions | default([]) }},
  ring_w={{ ring_w | default(10) }},
  ring_t={{ ring_t | default(2) }},
  reinforce_enable={{ reinforce_enable | default(false) | lower }},
  reinforce_side="{{ reinforce_side | default('boven') }}",
  reinforce_spans={{ reinforce_spans | default([]) }},
  productzijde="{{ productzijde | default('buiten') }}",
  bom_tag="{{ bom_tag }}_dxf",
  $fn=96
);
'''
    
    template = Template(dxf_template)
    dxf_scad_content = template.render(
        config_name=config_name,
        config_file=args.config,
        **params
    )
    
    # Generate DXF .scad in project root (for library resolution)
    dxf_scad_file = project_root / f".gen_{config_name}_dxf.scad"
    dxf_scad_file.write_text(dxf_scad_content, encoding="utf-8")
    
    debug_log(f"Generated DXF SCAD file: {dxf_scad_file.absolute()}", "DEBUG")
    
    dxf_file = output_dir / f"{config_name}.dxf"
    cmd = ["openscad", "-o", str(dxf_file.absolute()), str(dxf_scad_file.absolute())]
    
    debug_log(f"DXF render command: {' '.join(cmd)}", "DEBUG")
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(Path.cwd()))
    
    debug_log(f"DXF render return code: {result.returncode}", "DEBUG")
    if result.returncode != 0:
        debug_log(f"DXF render stdout:\n{result.stdout}", "ERROR")
        debug_log(f"DXF render stderr:\n{result.stderr}", "ERROR")
        sys.exit(1)
    
    debug_log(f"✓ Generated DXF to {dxf_file}", "INFO")
else:
    debug_log("⊘ Skipping DXF export", "INFO")

debug_log("", "INFO")
debug_log("✓ Model generation complete!", "INFO")
debug_log(f"  Config:  {args.config}", "INFO")
debug_log(f"  Output:  {output_dir}/", "INFO")
debug_log(f"  Files:   {config_name}.*", "INFO")
debug_log("=== GENERATE_MODEL DEBUG END ===", "DEBUG")

# Cleanup temporary .scad files from project root
debug_log("", "DEBUG")
debug_log("Cleaning up temporary .scad files from project root...", "DEBUG")
for tmp_file in [scad_file]:
    if tmp_file.exists():
        tmp_file.unlink()
        debug_log(f"Removed {tmp_file.name}", "DEBUG")

# Also remove DXF .scad if it was created
if not args.skip_dxf:
    if dxf_scad_file.exists():
        dxf_scad_file.unlink()
        debug_log(f"Removed {dxf_scad_file.name}", "DEBUG")


# --- Step 1: Parse config → parameters ---
print("==> [1/5] Parsing configuration...", file=sys.stderr)
config_json = output_dir / ".config_params.json"
cmd = [
    sys.executable, "scripts/config_to_params.py",
    "--config", args.config,
    "--presets", args.presets,
    "--output", str(config_json),
]
if args.debug:
    cmd.append("--debug")

result = subprocess.run(cmd, capture_output=True, text=True)
if result.returncode != 0:
    sys.stderr.write(result.stderr)
    sys.exit(1)
sys.stderr.write(result.stdout)

params = json.loads(config_json.read_text(encoding="utf-8"))
config_name = params.get("bom_tag", "unnamed")

# --- Step 2: Generate OpenSCAD file ---
print("==> [2/5] Generating OpenSCAD file...", file=sys.stderr)

scad_template = '''// Generated by config: {{ config_name }}
// DO NOT EDIT - Generated from {{ config_file }}
use <products/filterslang/filterslang.scad>;

filterslang(
  L={{ L }},
  D={{ D }},
  t={{ t }},
  medium="{{ medium }}",
  top="{{ top }}",
  open_top={{ open_top | default(false) | lower }},
  bottom="{{ bottom }}",
  bottom_opt="{{ bottom_opt | default('zonder') }}",
  rings_auto={{ rings_auto | default(true) | lower }},
  rings_count={{ rings_count | default(0) }},
  rings_positions={{ rings_positions | default([]) }},
  ring_w={{ ring_w | default(10) }},
  ring_t={{ ring_t | default(2) }},
  reinforce_enable={{ reinforce_enable | default(false) | lower }},
  reinforce_side="{{ reinforce_side | default('boven') }}",
  reinforce_spans={{ reinforce_spans | default([]) }},
  productzijde="{{ productzijde | default('buiten') }}",
  bom_tag="{{ bom_tag }}",
  $fn=96
);
'''

template = Template(scad_template)
scad_content = template.render(
    config_name=config_name,
    config_file=args.config,
    **params
)

scad_file = output_dir / f"{config_name}.scad"
scad_file.write_text(scad_content, encoding="utf-8")
print(f"✓ Generated {scad_file}", file=sys.stderr)

# --- Step 3: Render with OpenSCAD ---
if not args.skip_render:
    print("==> [3/5] Rendering with OpenSCAD...", file=sys.stderr)
    echo_file = output_dir / f"{config_name}.echo"
    
    # OpenSCAD must run from project root to find libraries
    cmd = ["openscad", "-o", str(echo_file.resolve()), str(scad_file.resolve())]
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=Path.cwd())
    if result.returncode != 0:
        sys.stderr.write(f"ERROR: OpenSCAD render failed\n{result.stderr}\n")
        sys.exit(1)
    print(f"✓ Rendered to {echo_file}", file=sys.stderr)
else:
    echo_file = output_dir / f"{config_name}.echo"
    if not echo_file.exists():
        sys.stderr.write(f"ERROR: --skip-render but {echo_file} not found\n")
        sys.exit(1)
    print(f"⊘ Skipping render; using {echo_file}", file=sys.stderr)

# --- Step 4: Extract BOM ---
if not args.skip_bom:
    print("==> [4/5] Extracting BOM...", file=sys.stderr)
    jsonl_file = output_dir / f"{config_name}_bom.jsonl"
    csv_file = output_dir / f"{config_name}_bom.csv"
    xlsx_file = output_dir / f"{config_name}_bom_production.xlsx"
    
    cmd = [
        sys.executable, "scripts/render_bom.py",
        "--product", "filterslang",
        "--version", "1.0.0",
        "--echo", str(echo_file),
        "--jsonl", str(jsonl_file),
        "--csv", str(csv_file),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(f"ERROR: BOM extraction failed\n{result.stderr}\n")
        sys.exit(1)
    
    # Also produce Excel BOM
    cmd = [
        sys.executable, "scripts/bom_producer.py",
        "--jsonl", str(jsonl_file),
        "--parts", "data/parts.csv",
        "--xlsx", str(xlsx_file),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(f"ERROR: BOM production failed\n{result.stderr}\n")
        sys.exit(1)
    
    print(f"✓ Extracted BOM to {jsonl_file}, {csv_file}, {xlsx_file}", file=sys.stderr)
else:
    print("⊘ Skipping BOM extraction", file=sys.stderr)

# --- Step 5: Generate DXF (2D projection) ---
if not args.skip_dxf:
    print("==> [5/5] Generating DXF (2D projection)...", file=sys.stderr)
    
    dxf_template = '''// 2D projection for DXF export - {{ config_name }}
// DO NOT EDIT - Generated from {{ config_file }}
use <products/filterslang/filterslang.scad>;

projection(cut=false)
filterslang(
  L={{ L }},
  D={{ D }},
  t={{ t }},
  medium="{{ medium }}",
  top="{{ top }}",
  open_top={{ open_top | default(false) | lower }},
  bottom="{{ bottom }}",
  bottom_opt="{{ bottom_opt | default('zonder') }}",
  rings_auto={{ rings_auto | default(true) | lower }},
  rings_count={{ rings_count | default(0) }},
  rings_positions={{ rings_positions | default([]) }},
  ring_w={{ ring_w | default(10) }},
  ring_t={{ ring_t | default(2) }},
  reinforce_enable={{ reinforce_enable | default(false) | lower }},
  reinforce_side="{{ reinforce_side | default('boven') }}",
  reinforce_spans={{ reinforce_spans | default([]) }},
  productzijde="{{ productzijde | default('buiten') }}",
  bom_tag="{{ bom_tag }}_dxf",
  $fn=96
);
'''
    
    template = Template(dxf_template)
    dxf_scad_content = template.render(
        config_name=config_name,
        config_file=args.config,
        **params
    )
    
    dxf_scad_file = output_dir / f"{config_name}_dxf.scad"
    dxf_scad_file.write_text(dxf_scad_content, encoding="utf-8")
    
    dxf_file = output_dir / f"{config_name}.dxf"
    cmd = ["openscad", "-o", str(dxf_file.resolve()), str(dxf_scad_file.resolve())]
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=Path.cwd())
    if result.returncode != 0:
        sys.stderr.write(f"ERROR: DXF render failed\n{result.stderr}\n")
        sys.exit(1)
    
    print(f"✓ Generated DXF to {dxf_file}", file=sys.stderr)
else:
    print("⊘ Skipping DXF export", file=sys.stderr)

print("", file=sys.stderr)
print("✓ Model generation complete!", file=sys.stderr)
print(f"  Config:  {args.config}", file=sys.stderr)
print(f"  Output:  {output_dir}/", file=sys.stderr)
print(f"  Files:   {config_name}.*", file=sys.stderr)
